--liquibase formatted sql
--changeset Sivodedov Dmitry:create_table_language
CREATE TABLE LANGUAGE
(
  ID   BIGINT PRIMARY KEY NOT NULL IDENTITY,
  CODE VARCHAR_IGNORECASE(3),
  NAME VARCHAR(255)
);
--rollback drop table language;
--changeset Sivodedov Dmitry:fill_table_language
INSERT INTO LANGUAGE (ID, CODE, NAME)
VALUES (1, 'RUS', 'Русский'), (2, 'ENG', 'English');
--rollback delete from language;

--changeset Sivodedov Dmitry:create_table_dictionary
CREATE TABLE DICTIONARY
(
  ID            BIGINT PRIMARY KEY NOT NULL IDENTITY,
  NAME          VARCHAR(255),
  FROM_LANGUAGE BIGINT,
  TO_LANGUAGE   BIGINT,
  USER          BIGINT,
  CONSTRAINT FK_DICTIONARY_FROM_L FOREIGN KEY (FROM_LANGUAGE) REFERENCES LANGUAGE (ID),
  CONSTRAINT FK_DICTIONARY_TO_L FOREIGN KEY (TO_LANGUAGE) REFERENCES LANGUAGE (ID),
  CONSTRAINT FK_DICTIONARY_USER FOREIGN KEY (USER) REFERENCES PRINCIPAL (ID)
);
--rollback drop table dictionary;
--changeset Sivodedov Dmitry:create_table_word
CREATE TABLE WORD
(
  ID             BIGINT PRIMARY KEY NOT NULL IDENTITY,
  COUNT_ATTEMPTS INTEGER,
  COUNT_FAIL     INTEGER,
  COUNT_SUCCESS  INTEGER,
  CREATED        TIMESTAMP,
  LAST_ATTEMPT   TIMESTAMP,
  LAST_SUCCESS   TIMESTAMP,
  TEXT           VARCHAR(255),
  LTEXT          VARCHAR_IGNORECASE(255),
  LANGUAGE       BIGINT,
  dictionary     BIGINT,
  CONSTRAINT FK_WORD_LANGUAGE FOREIGN KEY (LANGUAGE) REFERENCES LANGUAGE (ID),
  CONSTRAINT FK_WORD_DICTIONARY FOREIGN KEY (DICTIONARY) REFERENCES DICTIONARY (ID)
);
--rollback drop table word;
--changeset Sivodedov Dmitry:create_table_word_link
CREATE TABLE WORD_LINK
(
  ID   BIGINT PRIMARY KEY NOT NULL IDENTITY,
  TYPE INTEGER
);
--rollback drop table word_link;
--changeset Sivodedov Dmitry:create_table_word_link_dictionary
CREATE TABLE WORD_LINK_DICTIONARY
(
  DICTIONARY_ID BIGINT NOT NULL,
  LINK_ID       BIGINT NOT NULL,
  CONSTRAINT FK_WORD_LINK_D FOREIGN KEY (DICTIONARY_ID) REFERENCES DICTIONARY (ID),
  CONSTRAINT FK_WORD_LINK_L FOREIGN KEY (LINK_ID) REFERENCES WORD_LINK (ID)
);
--rollback drop table word_link_dictionary;
--changeset Sivodedov Dmitry:create_table_word_link_from
CREATE TABLE WORD_LINK_FROM
(
  LINK_ID BIGINT NOT NULL,
  WORD_ID BIGINT NOT NULL,
  CONSTRAINT FK_WLF_LINK FOREIGN KEY (LINK_ID) REFERENCES WORD_LINK (ID),
  CONSTRAINT FK_WLF_WORD FOREIGN KEY (WORD_ID) REFERENCES WORD (ID)
);
--rollback drop table word_link_from;
--changeset Sivodedov Dmitry:create_table_word_link_to
CREATE TABLE WORD_LINK_TO
(
  LINK_ID BIGINT NOT NULL,
  WORD_ID BIGINT NOT NULL,
  CONSTRAINT FK_WLT_LINK FOREIGN KEY (LINK_ID) REFERENCES WORD_LINK (ID),
  CONSTRAINT FK_WLT_WORD FOREIGN KEY (WORD_ID) REFERENCES WORD (ID)
);
--rollback drop table word_link_to;

