app:
  name: anuglar2-spring-jwt

jwt:
  header: Authorization
  expires_in: 600 # 10 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN

logging:
  level:
    org.springframework.web: ERROR
    com.bfwg: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:hsqldb:hsql://localhost:9001/xdb
    username: SA
    password: password
    driver-class-name: org.hsqldb.jdbc.JDBCDriver